apiVersion: v2
name: duihua-ai-services
description: OpenAI API compatible self-hosted AI services for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: duihua-gateway
    version: 0.0.0-111d97424c26ea8805394dff7d957d22c7234ed5
    repository: oci://ghcr.io/beranekio/charts
  - name: duihua-background-worker
    version: 0.0.0-f884444170331e160e74bdc62134faa63268abf3
    repository: oci://ghcr.io/beranekio/charts
    condition: duihua-background-worker.enabled
  - name: responses-api-store
    version: 0.0.0-c18a05fecfd3d85ddc0d418d90081cc4f7610061
    repository: oci://ghcr.io/beranekio/charts
    condition: responsesApiStoreService.enabled
