{{- if eq (include "duihua.background.autoscaling.enabled" .) "true" }}
{{- $autoscaling := .Values.backgroundWorker.autoscaling }}
{{- $workerName := printf "%s-background-worker" (include "duihua.fullname" .) }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $workerName }}
  {{- with $autoscaling.scaledObjectAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    name: {{ $workerName }}
    kind: Deployment
    apiVersion: apps/v1
  minReplicaCount: {{ include "duihua.background.autoscaling.minReplicas" . }}
  maxReplicaCount: {{ include "duihua.background.autoscaling.maxReplicas" . }}
  cooldownPeriod: {{ include "duihua.background.autoscaling.scaledownPeriod" . }}
  {{- with $autoscaling.pollingInterval }}
  pollingInterval: {{ . }}
  {{- end }}
  triggers:
    - type: redis-streams
      metadata:
        address: {{ include "duihua.responseIdStoreAddress" . | quote }}
        stream: {{ include "duihua.background.streamKey" . | quote }}
        consumerGroup: {{ .Values.backgroundWorker.consumerGroup | quote }}
        lagCount: {{ $autoscaling.lagCount | default 5 | quote }}
        activationLagCount: {{ include "duihua.background.autoscaling.activationLagCount" . | quote }}
        {{- if or $autoscaling.enableTLS (eq (include "duihua.responseIdStoreTLSEnabled" .) "true") }}
        enableTLS: "true"
        {{- end }}
        {{- $databaseIndex := include "duihua.responseIdStoreDatabaseIndex" . -}}
        {{- if ne $databaseIndex "0" }}
        databaseIndex: {{ $databaseIndex | quote }}
        {{- end }}
        {{- with $autoscaling.passwordFromEnv }}
        passwordFromEnv: {{ . | quote }}
        {{- end }}
{{- end }}