apiVersion: v1
kind: Service
metadata:
  name: {{ include "duihua.fullname" . }}-gateway
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    app: {{ include "duihua.fullname" . }}-gateway
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
      {{- if and (or (eq .Values.gateway.service.type "NodePort") (eq .Values.gateway.service.type "LoadBalancer")) .Values.gateway.service.nodePort }}
      nodePort: {{ .Values.gateway.service.nodePort }}
      {{- end }}
