{{- if and (eq (include "duihua.backgroundJobs.enabled" .) "true") .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "duihua.serviceAccountName" . }}
{{- end }}